# GitHub Pages Configuration
title: RightNow Issues & Feedback
description: Official issue tracker and feedback hub for RightNow - the capacity-first productivity app
url: https://yourusername.github.io
baseurl: /rtnwapp

# Build settings
markdown: kramdown
theme: null  # We're using custom HTML/CSS

# Exclude files from site build
exclude:
  - README.md
  - CLAUDE.md
  - .gitignore
  - .claude/

# GitHub Pages will serve index.html by default